### ISSUE TITLE
With command invoice the object CLightningInvoice have some null propriety!

### ISSUE THREAD

**Issue by vincenzopalazzo** [clightning4j/JRPClightning#4]
```
{
  "jsonrpc": 2.0,
  "id": 11,
  "result": {
    "payment_hash": "7707b76fad49b89d6a5402680203a90734aec85b28da0f0ae3ac6019cd4b97b7",
    "expires_at": "1600034700",
    "bolt11": "lntb10n1p042hgvpp5wurmwmadfxuf66j5qf5qyqafqu62ajzm9rdq7zhr43spnn2tj7msdqjv3jhxcmjd9c8g6t0dcxqyjw5qcqp2sp5a8m5mpv0nkx7f7x4qgr6wquzexhe920xqpkf3n8av60r26shjrts9qy9qsq6g3jse4920uvve2t8jhd9nr74zr2yq5m2663vd0pxz5k0lfczy5p9xfwjjd2alvps9jr5tdqdvng2vx3wzpm9vq0v3mqy03lpl6dqgcp9ynjp2",
    "warning_capacity": "No channels"
  }
}
00:05:00.266 [Test worker] DEBUG jrpc.clightning.TestCLightningRPC - invoice: lntb10n1p042hgvpp5wurmwmadfxuf66j5qf5qyqafqu62ajzm9rdq7zhr43spnn2tj7msdqjv3jhxcmjd9c8g6t0dcxqyjw5qcqp2sp5a8m5mpv0nkx7f7x4qgr6wquzexhe920xqpkf3n8av60r26shjrts9qy9qsq6g3jse4920uvve2t8jhd9nr74zr2yq5m2663vd0pxz5k0lfczy5p9xfwjjd2alvps9jr5tdqdvng2vx3wzpm9vq0v3mqy03lpl6dqgcp9ynjp2

junit.framework.AssertionFailedError
	at junit.framework.Assert.fail(Assert.java:55)
	at junit.framework.Assert.assertTrue(Assert.java:22)
	at junit.framework.Assert.assertNotNull(Assert.java:256)
	at junit.framework.Assert.assertNotNull(Assert.java:248)
	at junit.framework.TestCase.assertNotNull(TestCase.java:417)
	at jrpc.clightning.TestCLightningRPC.testCommandGetInvoiceFour(TestCLightningRPC.java:106)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:119)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.base/java.lang.Thread.run(Thread.java:830)
```

**Comment by vincenzopalazzo** [comment]
The command invoice return not all propriety of the invoice, in fact, the json response is:

```
{
  "jsonrpc": 2.0,
  "id": 73,
  "result": {
    "payment_hash": "57d686fe5be5eb16b5c9b8f6bfee77941c94d8f0924378038ad10798aa14c366",
    "expires_at": "1600034968",
    "bolt11": "lntb10n1p042hscpp52ltgdljmuh43ddwfhrmtlmnhjswffk8sjfphsqu26yre32s5cdnqdqjv3jhxcmjd9c8g6t0dcxqyjw5qcqp2sp566jpteaffyv5znylcuy03deuv48whl66jydwdux5qx9ec7qx4mms9qy9qsqqz36nppzg3s5zjqvpdgllxxcgatfwkatx5mq4zdhw2kk6nh4q4akfsmmyrx24854ev3sp0xa3emhxhpp2qs0mr2qqyywr757ev8pgqgpugnlvr",
    "warning_capacity": "No channels"
  }
}
```

Maybe this object needs another type? or I can insert inside the library the inflate propriety but in this case, I don't java all proprieties

**Comment by vincenzopalazzo** [comment]
It is normal also because in the actual version of the library different commands share the same Java Wrapper but it contains different proprieties, and some can be null
